apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      imagePullSecrets:
        - name: dockerhub-credinials
      containers:

        - image: redaeid/kubernets-app_web-app:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          name: nodejs-app
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "1"
          env:
    
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: non-sensitive-env
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: non-sensitive-env
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensitive-var
                  key: DB_PASSWORD

          volumeMounts:
          
            - mountPath: /app/logs
              name: nodejs-app-volume
        
      initContainers:
        - name: ivolve
          image: mysql:5.7
          env:
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensitive-var
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: non-sensitive-env
                  key: DB_HOST
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: non-sensitive-env
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sensitive-var
                  key: DB_PASSWORD
          command:
            - "sh"
            - "-c"
            - |
              mysql -h$DB_HOST -u root -p$ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \'ivolve\';"
              mysql -h$DB_HOST -u root -p$ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON \'ivolve\'* to '$DB_USER'@'%';"
              mysql -h $DB_HOST -u root -p$ROOT_PASSWORD -e "FLUSH PRIVILEGES;"
        
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "worker"
          effect: "NoSchedule"
      volumes:
        - name: nodejs-app-volume
          persistentVolumeClaim:
            claimName: pvc-retain

status: {}
