apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retain
  namespace: ivolve
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
      path: /mnt/app-logs  
      
